baseURL = '/'
languageCode = 'en-us'
title = 'Code Block Annotation'
disableKinds = ['taxonomy','taxonomyTerm']

[params]
   images = ['/cba/annotation_share.png']
   description = 'Code block annotation module for Hugo sites.'

[markup]
   defaultMarkdownHandler = "goldmark"
   
   [markup.goldmark]
      [markup.goldmark.renderer]
         unsafe = true